// ===== KID-FIRST UI =====
// Replaces the screens in ui.js (later scripts override earlier functions). Principles: one idea at a time, a friendly guide (Pip)
// who explains what is happening in plain words, big buttons, only the meters that matter for the current mission, and the
// full numbers tucked into an "Engineer panel". The simulation (sim.js) is unchanged.
const MET={1:['bat'],2:['bat','heat'],3:['bat','heat','water','air'],4:['bat','heat','water','air','food'],5:['bat','heat','water','air','food','rad','sys'],6:['bat','heat','water','air','food','rad','sys']};
const ACT={1:['heat'],2:['heat','clean'],3:['heat','clean','miner'],4:['heat','clean','miner','lights'],5:['heat','clean','miner','lights','shelter','repair'],6:['heat','clean','miner','lights','shelter','repair']};
const REC={1:{p:8,b:3},2:{p:8,b:4},3:{p:9,b:3,r:1},4:{p:10,b:3,g:1,r:1},5:{p:9,b:3,r:1,s:1,k:1},6:null};
const ICON=['🌅','🌪️','💧','🌱','☢️','🧑‍🚀'],NONE={p:0,b:0,s:0,g:0,r:0,k:0,d:0,x:0},W3=['✅','⚠️','🚨'];
const KD={p:'Makes power when the sun is up.',b:'Saves power for the night and for storms.',g:'Grows food. Needs power, water and warmth.',r:'Cleans used water so you can drink it again.',x:'Digs up ice to make water.',k:'Each one fixes a broken machine.',d:'A spare air machine, just in case.'};
const FACE=h=>h>85?'😀':h>60?'🙂':h>35?'😟':h>0?'🤒':'😵',band=(v,a,b)=>v>=a?0:v>=b?1:2;
const COACH={1:[['#v3d','This is your outpost on Mars! Four astronauts live inside.'],['#m-bat','This is the battery. It stores energy for the night. If it hits zero, the crew is in trouble!'],['#bal','Panels make power in sunlight. The outpost uses power too. Try to make at least as much as you use.'],['#s1','Press Play to start. Keep the battery above zero for 5 sols!']],2:[['#bal','A dust storm is coming. It blocks the sun, so the panels make much less power.'],['#act','Use these buttons. Turn the heater down to save power. Clean the dust off the panels after the storm.']]};
// --- title, map, mission intro ---
function brief(){A.innerHTML=`<div class="hero"><div class="bigpip">🤖</div><h1>OUTPOST ZERO</h1><div class="bub"><p>Hi, Commander! I'm Pip. Four astronauts are flying to Mars and they need a home. Help me build it and keep them safe!</p></div><p><button class="go big" onclick="menu()">🚀 PLAY</button></p><p><button onclick="nasa()">🔬 NASA data</button></p></div>`}
function menu(){const d=loadProg();A.innerHTML=`<div class="hero"><h1>Choose a mission</h1></div><div class="map">${LEVELS.map((l,i)=>{const open=l.id==1||d.includes(l.id-1),done=d.includes(l.id);return `<button class="planet ${done?'done':open?'open':'lock'}" ${open?'':'disabled'} onclick="intro(${l.id})" aria-label="Mission ${l.id}: ${l.name}. ${done?'Complete':open?'Ready':'Locked'}"><span class="pi">${open?ICON[i]:'🔒'}</span><b>${l.id}. ${l.name}</b><small>${done?'✔ Done':open?'▶ Play':'Locked'}</small></button>`}).join('')}</div><p><button onclick="brief()">◀ Title</button> <button class="sm" onclick="unlockAll()">Unlock all (teacher)</button> <button class="sm" onclick="resetProg()">Reset</button></p>`}
function intro(n){LV=LEVELS[n-1];DAYS=LV.sols;A.innerHTML=`<div class="hero"><div class="bigpip">${ICON[n-1]}</div><h1>Mission ${n}: ${LV.name}</h1></div><div class="bub"><span class="pip">🤖</span><p>${LV.story}</p></div><div class="goal">🎯 <b>Goal:</b> ${LV.obj}</div><details class="card"><summary>🧠 What you will learn</summary><ul>${LV.learn.map(x=>`<li>${x}</li>`).join('')}</ul></details>${n<6?`<details class="card"><summary>💡 Need a hint?</summary><p>${LV.hint}</p></details>`:''}<p><button onclick="menu()">◀ Back</button> <button class="go big" onclick="${LV.sites.length>1?'pick()':'build('+LV.sites[0]+')'}">🛠️ ${LV.sites.length>1?'Choose a site':'Build your outpost'}</button></p>`}
// --- design screen ---
function drawB(){const c=cfg,left=LV.budget-price(),nh=Math.round((c.b*25+20)/5.5);
const tile=r=>{const[,k,ic,nm,mx,cs]=r;if(!LV.eq.includes(k))return '';return `<div class="card bt"><div class="bi">${ic}</div><div class="bm"><b>${nm}</b><br><small>${KD[k]}</small><div class="count" aria-label="${c[k]} ${nm}">${c[k]?ic.repeat(Math.min(c[k],14)):'—'}</div><small>🪙 ${cs} each</small><details><summary><small>ℹ️ Tell me more</small></summary><small><b>Good:</b> ${r[7]}<br><b>But:</b> ${r[8]}</small></details></div><div class="pm"><button class="big" aria-label="More ${nm}" onclick="cfg.${k}=Math.min(${mx},cfg.${k}+1);drawB()">＋</button><b class="big2">${c[k]}</b><button class="big" aria-label="Fewer ${nm}" onclick="cfg.${k}=Math.max(0,cfg.${k}-1);drawB()">－</button></div></div>`};
const sh=LV.sh.length>1?`<div class="card"><b>🛡️ Radiation walls</b><br><small>Protect the crew from space radiation. Protection always costs something.</small><div class="acts">${[['None',0],['💧 Water walls (12 coins, uses 100 kg water)',1],['🪨 Soil walls (22 coins)',2]].map(x=>`<button class="${c.s==x[1]?'on':''}" aria-pressed="${c.s==x[1]}" onclick="cfg.s=${x[1]};drawB()">${c.s==x[1]?'✓ ':''}${x[0]}</button>`).join('')}</div></div>`:'';
A.innerHTML=`<div class="hero"><h1>🛠️ Build your outpost</h1></div><div class="goal">🎯 ${LV.obj}</div><p class="coins ${left<0?'neg':''}">🪙 ${left} coins left${left<0?' (too many! remove something)':''}</p><div class="bub"><span class="pip">🤖</span><p><b>Pip's check:</b> with no sun, your battery lasts about ${nh} hours. A Mars night lasts about 12 hours. ${nh>=12?'✅ Looks good!':'⚠️ You may run out at night.'} <small>(rough estimate)</small></p></div>${CP.map(tile).join('')}${sh}<details class="card"><summary>⚙️ Advanced</summary>Weather seed <input id="seed" type="number" value="${seed}" style="width:90px;font:inherit" aria-label="Weather seed"> <small>Same seed = same weather.</small></details><div class="acts">${REC[LV.id]?`<button onclick="cfg=Object.assign({},NONE,REC[LV.id]);drawB()">✨ Use Pip's build</button>`:''}</div><p><button onclick="back()">◀ Back</button> <button class="go big" ${left<0?'disabled':''} onclick="start()">🚀 Launch!</button></p>`}
// --- mission screen ---
let cs=0,cl=[];
function layout(){const a=ACT[LV.id],has=k=>a.includes(k);A.innerHTML=`<div class="top"><div id="hd" class="chip"></div><div class="sp acts"><button id="s0" onclick="spd(0)" aria-label="Pause">⏸</button><button id="s1" class="on" onclick="spd(1)">▶ Play</button><button id="s2" onclick="spd(2)">▶▶ Fast</button><button id="s3" onclick="spd(3)">▶▶▶ Zoom</button></div></div>
<div id="pip" class="bub" role="status" aria-live="polite"><span class="pip">🤖</span><p id="pipt"></p></div>
<div class="card" style="padding:0;overflow:hidden;position:relative"><div id="v3d" style="height:260px;touch-action:none"></div><div id="clk" class="clk"></div></div>
<div class="card"><div class="row"><b>👩‍🚀 Crew</b><span id="crew" class="crew"></span></div></div>
<div id="bal" class="card"><div class="row"><span class="big2">☀️ Making power: <b id="mk">0</b></span><span class="big2">🏠 Using power: <b id="us">0</b></span></div><div id="bt" class="big2"></div></div>
<div class="tiles">${[['bat','🔋','Battery'],['heat','🌡️','Warmth'],['air','🫁','Air'],['water','💧','Water'],['food','🍎','Food'],['rad','☢️','Radiation safety'],['sys','🔧','Machines']].map(m=>`<div class="tile" id="m-${m[0]}" hidden><div class="ti">${m[1]}</div><b>${m[2]}</b><div class="bar big"><i id="b-${m[0]}" style="width:0"></i></div><div class="st" id="v-${m[0]}"></div></div>`).join('')}</div>
<div id="act" class="card"><b>Your controls</b>${has('heat')?`<div class="acts"><span>🌡️ Heater:</span><button id="h11" onclick="heat(11)">❄️ Save energy</button><button id="h20" class="on" onclick="heat(20)">🏠 Comfy</button><button id="h24" onclick="heat(24)">🔥 Toasty</button></div>`:''}<div class="acts">${has('clean')?'<button id="bcl" onclick="cleanP()">🧽 Clean panels</button>':''}${has('miner')&&cfg.x?'<button onclick="S.ex=+!S.ex">⛏️ Ice miner on/off</button>':''}${has('lights')&&cfg.g?'<button onclick="S.gh=+!S.gh&&cfg.g">💡 Greenhouse lights on/off</button>':''}${has('shelter')?'<button onclick="S.sh=+!S.sh">🛡️ Shelter crew on/off</button>':''}${has('repair')?'<button id="brp" onclick="repair()">🔧 Repair</button>':''}</div></div>
<details class="card" id="eng"><summary>🔬 Engineer panel (numbers, chart, log)</summary><div class="grid" id="st"></div><canvas id="cv" width="900" height="150"></canvas><div id="log"></div><span id="bg"></span><span id="bx"></span><span id="bs"></span></details>
<p><button onclick="coachStart(true)">❓ Help</button> <button onclick="nasa()">🔬 NASA data</button> <button onclick="quit()">⏏ Quit mission</button></p><div id="why"></div>`;coachStart()}
function heat(v){S.set=v;[11,20,24].forEach(x=>{const e=$('#h'+x);if(e)e.className=x==v?'on':''})}
function quit(){clearInterval(timer);if(V){cancelAnimationFrame(V.raf);V=null}S.end=1;const o=$('#coach');if(o)o.remove();menu()}
function coachStart(force){let seen=[];try{seen=JSON.parse(localStorage.getItem('ozCoach')||'[]')}catch(e){}if(!force&&seen.includes(LV.id))return;cl=COACH[LV.id]||[['#pip',LV.hint]];cs=0;try{if(!seen.includes(LV.id)){seen.push(LV.id);localStorage.setItem('ozCoach',JSON.stringify(seen))}}catch(e){}spd(0);coachShow()}
function coachShow(){document.querySelectorAll('.hl').forEach(e=>e.classList.remove('hl'));let o=$('#coach');if(cs>=cl.length){if(o)o.remove();spd(1);return}
if(!o){o=document.createElement('div');o.id='coach';o.setAttribute('role','dialog');o.setAttribute('aria-label','Pip the guide');document.body.appendChild(o)}
const t=$(cl[cs][0]);if(t){t.classList.add('hl');t.scrollIntoView({block:'center',behavior:'smooth'})}
o.innerHTML=`<div class="bub"><span class="pip">🤖</span><div><p>${cl[cs][1]}</p><div class="acts"><button class="sm" onclick="cs=cl.length;coachShow()">Skip</button><button class="go" id="cn" onclick="cs++;coachShow()">${cs<cl.length-1?'Next ▶':'Got it!'}</button></div></div></div>`;$('#cn').focus()}
// --- plain-language advice from Pip, based on what is actually happening in the simulation ---
function advice(){const s=S,l=s.last||{gen:0,used:0,ppm:0},h=s.t%24,day=h>=6&&h<18,a=ACT[LV.id],bat=s.bat/(cfg.b*25+20)*100,bad=Object.values(s.fail).some(x=>x);
if(s.t>0&&s.bat<=.5&&l.gen<l.used)return 'The lights went out! The battery is empty, so the air machines stopped. Make more power or use less!';
if(s.spe&&a.includes('shelter'))return s.sh?'Good! The crew is sheltering from the radiation.':'Radiation alert! Tap "Shelter crew" to keep everyone safe.';
if(bad&&a.includes('repair'))return 'Something broke! Tap Repair to fix it with a spare part.';
if(s.storm)return s.set>13&&a.includes('heat')?'Dust storm! Sunlight is blocked. Tap "Save energy" so the battery lasts longer.':'Dust storm! The panels make very little power. Use as little as you can.';
if(s.cover>.25&&day&&a.includes('clean'))return 'Dust is covering the panels, so they make less power. Tap "Clean panels"!';
if(s.tin<8)return 'Brrr! The habitat is getting cold. Heating uses a lot of power at night.';
if(l.ppm>5000)return 'The air is getting stale. The air cleaner needs power to work.';
if(s.h2o<40)return 'Water is running low. Recycle it or mine ice!';
if(s.food<20&&a.includes('lights'))return 'Food is running low. Keep the greenhouse lights on!';
if(bat<25)return day?'The battery is low, but the sun is up and charging it. Hold on!':'It is night. Panels make no power, so the battery is doing all the work, and it is getting low.';
return day?(l.gen>l.used?'Daytime! The panels make more power than we use, so the battery is charging.':'The sun is up, but we use more power than the panels make.'):'Night time. The battery is powering the outpost.'}
// --- per-frame update ---
const render0=render;render=function(){render0();kr()};
let lastAdv='';
function kr(){const s=S,l=s.last||{gen:0,used:0,ppm:0},day=s.t%24>=6&&s.t%24<18,cap=cfg.b*25+20,bat=s.bat/cap*100,fail=Object.keys(s.fail).filter(k=>s.fail[k]),NM={scr:'air cleaner',oga:'air maker',rec:'water recycler',heat:'heater'};
const o2=s.o2,ppm=l.ppm||0,airSt=Math.max(band(o2,40,20),ppm>15000?2:ppm>5000?1:0),T=s.tin,heatSt=T>=12&&T<=32?0:(T>=6&&T<=35)?1:2;
const M={bat:[bat,band(bat,50,25),['Plenty of power','Getting low','Almost empty!'][band(bat,50,25)]],
heat:[(T+10)/50*100,heatSt,Math.round(T)+'°C · '+['Cozy','Careful','Danger!'][heatSt]],air:[Math.min(o2,100),airSt,['Fresh','Getting stale','Bad air!'][airSt]],
water:[s.h2o/300*100,band(s.h2o,100,40),['Plenty','Getting low','Almost out!'][band(s.h2o,100,40)]],food:[s.food/(LV.food||100)*100,band(s.food,40,20),['Plenty','Getting low','Almost out!'][band(s.food,40,20)]],
rad:[100-s.dose/.6,s.dose<30?0:s.dose<45?1:2,['Safe','Watch out','Danger!'][s.dose<30?0:s.dose<45?1:2]],sys:[fail.length?30:100,fail.length?2:0,fail.length?'Broken: '+fail.map(k=>NM[k]).join(', '):'All working']};
for(const k in M){const e=$('#m-'+k);if(!e)continue;const m=M[k];e.hidden=!(MET[LV.id].includes(k)||(m[1]==2&&s.t>0));e.className='tile s'+m[1];$('#b-'+k).style.width=Math.max(2,Math.min(100,m[0]))+'%';$('#v-'+k).textContent=W3[m[1]]+' '+m[2]}
$('#mk').textContent=l.gen.toFixed(1);$('#us').textContent=l.used.toFixed(1);$('#bt').textContent=s.bat<=.5?'🚨 Battery empty!':l.gen>=l.used?'✅ Making enough power. The battery is charging.':'⚠️ Using more than we make. The battery is draining.';
$('#clk').textContent=(day?'☀️ Day':'🌙 Night')+' · Sol '+(Math.floor(s.t/24)+1)+' of '+DAYS;$('#crew').textContent=FACE(s.hp).repeat(N)+' '+Math.round(s.hp)+'%';
const ad=advice();if(ad!==lastAdv){lastAdv=ad;$('#pipt').textContent=ad}const cb=$('#bcl');if(cb)cb.className=s.cover>.25&&day?'pulse':'';const rb=$('#brp');if(rb)rb.className=fail.length?'pulse':''}
// --- end of mission ---
function fin(){clearInterval(timer);if(V){cancelAnimationFrame(V.raf);V=null}S.end=1;const w=S.hp>0&&(!LV.win||LV.win(S)),k=Object.entries(S.dmg).sort((a,b)=>b[1]-a[1])[0],c=k?k[0]:'';
const KL={o2:['💨','The air ran out.','Air machines need power. When the battery died, the air stopped being made.'],co2:['🫁','Bad air built up.','The air cleaner needs power too. When power fails, the air gets stale.'],cold:['🥶','The outpost got too cold.','Heaters use a lot of power at night and in storms.'],heat:['🥵','It got too hot.','Temperature control works both ways.'],food:['🍎','The food ran out.','Greenhouses need power, light, water and warmth.'],water:['💧','The water ran out.','Recycling or mining ice makes water last, but both use power.'],rad:['☢️','Too much radiation.','Walls or sheltering protect the crew. Protection always costs something.']};
const f=KL[c]||['😵','The crew did not make it.',''],ev=S.rec.filter(e=>/Dust storm|BLACKOUT|failed|Battery|CO2|Oxygen|cold|Solar particle|low/i.test(e[1])).slice(0,5).map(e=>`<li><b>Sol ${Math.floor(e[0]/24)+1}</b> · ${e[1]}</li>`).join('');
const why=S.hp>0?LV.winMsg?'Not quite: '+LV.winMsg:'':f[1],les=S.hp>0?LV.lesson||'':f[2]+' '+(LV.lesson||'');
A.innerHTML=w?`<div class="hero"><div class="conf">🎉🚀🎉</div><h1>Mission complete!</h1><div class="crew">${FACE(S.hp).repeat(N)}</div><p>All ${N} astronauts made it!</p></div><div class="card"><b>🧠 You learned</b><ul>${LV.learn.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card"><b>⭐ Extra challenges</b><ul>${LV.goals.map(x=>`<li>${x[1](S)?'✔':'✖'} ${x[0]}</li>`).join('')}</ul></div><p>${endBtns(w)}</p>`:
`<div class="hero"><div class="bigpip">${f[0]}</div><h1>Oh no! Let's find out why</h1></div><div class="bub"><span class="pip">🤖</span><div><p><b>${why||f[1]}</b></p>${ev?`<p>What happened:</p><ul>${ev}</ul>`:''}<p>💡 ${les}</p></div></div><p>${endBtns(w)}</p>`}
