// ===== UI: screens, NASA panel, design screen, dashboard, debrief =====
const why = k => `<button class="sm" onclick="showWhy('${k}')">Why?</button>`;
function showWhy(k) { $('#why').innerHTML = `<div class="card"><b>Why it matters</b> ${['Rookie', 'Explorer', 'Engineer'].map((x, i) => `<button class="sm ${i == lv ? 'on' : ''}" onclick="lv=${i};showWhy('${k}')">${x}</button>`).join(' ')}<p>${WHY[k][lv]}</p></div>` }
function nasa() {
    const o = document.createElement('div'); o.className = 'ov'; o.id = 'nasa'; o.setAttribute('role', 'dialog'); o.setAttribute('aria-modal', 'true'); o.setAttribute('aria-label', 'NASA data');
    o.innerHTML = `<div><div class="row"><h2 style="margin:0">🔬 NASA DATA</h2><button id="nx" onclick="closeNasa()">Close</button></div><p class="sub">Not everything here is NASA data. Each input is labeled so you can tell what is measured and what is modeled.</p><table class="cmp">${Object.keys(TYPE_TXT).map(k => `<tr><td><span class="tg ${TYPE_COL[k]}">${k}</span></td><td>${TYPE_TXT[k]}</td></tr>`).join('')}</table>${Object.values(DATA_SOURCES).map(d => `<div class="card" style="margin-top:8px"><div class="row"><b>${d.label}</b><span class="tg ${TYPE_COL[d.type]}">${d.type}</span></div><small>${d.org}</small><p style="margin:4px 0">${d.used}</p><small>${d.note}<br>${d.url ? `<a href="${d.url}" target="_blank" rel="noopener">Source</a>` : 'Source link: to be verified before submission.'}</small></div>`).join('')}<div class="card" style="margin-top:8px"><b>Science chain: dust</b><p style="margin:4px 0">Mars dust → higher atmospheric opacity → less sunlight on panels → lower solar output → battery drains → heating, air and water systems lose power → crew health falls.</p></div></div>`;
    document.body.appendChild(o); $('#nx').focus(); o.onkeydown = e => { if (e.key == 'Escape') closeNasa() }
}
function closeNasa() { const o = $('#nasa'); if (o) o.remove() }
function brief() { A.innerHTML = `<h1>🚀 OUTPOST ZERO</h1><h2>Mission: Mars habitat demonstration</h2><p>You are the commander of a four-person Mars outpost.</p><p class="sub">Mission Control can provide data, but your crew must manage the habitat using the resources you brought with you.</p><div class="card"><b>Objective:</b> keep all four astronauts alive for 30 sols.</div><div class="grid" style="margin-top:10px"><div class="card">👩‍🚀 Crew: 4</div><div class="card">📅 Duration: 30 sols</div><div class="card">📦 Construction budget: 140</div><div class="card">🌪️ Storms and radiation spikes are possible</div><div class="card">🔧 Spare parts are limited</div></div><h2>Your job</h2><ol><li>Choose where to land.</li><li>Design the outpost.</li><li>Predict what could go wrong.</li><li>Adapt when Mars changes.</li></ol><p><button class="go" onclick="menu()">BEGIN MISSION</button> <button onclick="nasa()">🔬 NASA data</button></p>` }
let cmp = [];
function tg(i) { const k = cmp.indexOf(i); if (k >= 0) cmp.splice(k, 1); else { cmp.push(i); if (cmp.length > 2) cmp.shift() } pick() }
function pick() {
    const R = [['☀️ Solar', 'so'], ['💧 Ice', 'ic'], ['🌡️ Temperature', 'te'], ['☢️ Radiation', 'ra'], ['⛰️ Terrain', 'tr'], ['Engineering challenge', 'ch']];
    A.innerHTML = `<h1>Choose a landing site</h1><p class="sub">Each site solves some problems and creates others. Tick Compare on two sites to see them side by side.</p><div class="grid">${SITES.map((s, i) => `<div class="card"><b>${s.n}</b><div class="row"><span>☀️ Solar</span><b>${SQ[i].so}</b></div><div class="row"><span>💧 Buried ice</span><b>${SQ[i].ic}</b></div><div class="row"><span>☢️ Radiation</span><b>${SQ[i].ra}</b></div><div class="row"><span>🌡️ Temperature</span><b>${SQ[i].te}</b></div><div class="row"><span>⛰️ Terrain</span><b>${SQ[i].tr}</b></div><small><b>Engineering trade-off:</b> ${SQ[i].tx}</small><p><label><input type="checkbox" ${cmp.includes(i) ? 'checked' : ''} onchange="tg(${i})"> Compare</label></p><p><button class="go" onclick="build(${i})">Land here</button> <button class="sm" onclick="showWhy('site')">Why?</button></p></div>`).join('')}</div>${cmp.length == 2 ? `<div class="card" style="margin-top:10px"><h2>Compare sites</h2><table class="cmp"><tr><th></th><th>${SITES[cmp[0]].n}</th><th>${SITES[cmp[1]].n}</th></tr>${R.map(r => `<tr><td>${r[0]}</td><td>${SQ[cmp[0]][r[1]]}</td><td>${SQ[cmp[1]][r[1]]}</td></tr>`).join('')}</table><p><b>There is no universally perfect landing site.</b></p></div>` : ''}<p><button onclick="nasa()">🔬 NASA data</button> <button onclick="intro(LV.id)">Back</button></p><div id="why"></div>`
}
const price = () => Math.round((cfg.p * 5 + cfg.b * 8 + [0, 12, 22][cfg.s] + cfg.g * 18 + cfg.r * 14 + cfg.k * 4 + cfg.d * 12 + cfg.x * 14) * site.cost);
function build(i) { site = SITES[i]; cfg = Object.assign({ p: 8, b: 3, s: 0, g: 0, r: 1, k: 1, d: 0, x: 0 }, LV.start || {}); for (const k of 'pbgrxkd') if (!LV.eq.includes(k)) cfg[k] = 0; if (LV.sh.length < 2) cfg.s = 0; drawB() }
function drawB() {
    const c = cfg, left = LV.budget - price(); const card = (r) => { const [, k, ic, nm, mx, cs, d, im, sa, id] = r; if (!LV.eq.includes(k)) return `<div class="card" style="opacity:.6"><b>${ic} ${nm}</b><br><small>🔒 Unlocks in Mission ${unlockAt(k)}</small></div>`; return `<div class="card"><div class="row"><b>${ic} ${nm}</b><span><button class="sm" aria-label="Fewer ${nm}" onclick="cfg.${k}=Math.max(0,cfg.${k}-1);drawB()">−</button> <b>${c[k]}</b> <button class="sm" aria-label="More ${nm}" onclick="cfg.${k}=Math.min(${mx},cfg.${k}+1);drawB()">+</button></span></div><small>Cost ${cs} each</small><p style="margin:4px 0">${d}</p><small><b>Improves:</b> ${im}<br><b>Sacrifices:</b> ${sa}<br><b>Engineering idea:</b> ${id}</small></div>` };
    let h = '', last = ''; for (const r of CP) { if (r[0] != last) { h += (last ? '</div>' : '') + `<h2>${r[0]}</h2><div class="grid">`; last = r[0] } h += card(r) } h += '</div>';
    A.innerHTML = `<h1>⚙️ DESIGN YOUR OUTPOST</h1><p class="sub">${site.n}. Budget left <b style="color:${left < 0 ? 'var(--wr)' : 'var(--ok)'}">${left}</b> of ${LV.budget}.${site.cost > 1 ? ' Costs here are 15% higher.' : ''} Weather seed <input id="seed" type="number" value="${seed}" style="width:80px;font:inherit" aria-label="Weather seed"> (same seed = same weather).</p>${h}<h2>RADIATION SHIELDING</h2><div class="card"><div class="row"><b>🛡️ Shielding</b><select aria-label="Shielding type" onchange="cfg.s=+this.value;drawB()"><option value=0>None</option><option value=1 ${c.s == 1 ? 'selected' : ''} ${LV.sh.includes(1) ? '' : 'disabled'}>Water walls (12)</option><option value=2 ${c.s == 2 ? 'selected' : ''} ${LV.sh.includes(2) ? '' : 'disabled'}>Regolith (22)</option></select></div><small>${LV.sh.length < 2 ? '🔒 Unlocks in Mission 5. ' : ''}Protects the crew from radiation. ${why('rad')}<br><b>Water walls:</b> radiation to about 55%, but they use 100 kg of your starting water.<br><b>Regolith:</b> radiation to about 35% and better insulation (less heating), but costs the most.<br><b>Engineering idea:</b> protection usually costs something.</small></div><p><button onclick="back()">Back</button> <button onclick="nasa()">🔬 NASA data</button> <button class="go" ${left < 0 ? 'disabled' : ''} onclick="start()">Start mission</button></p><div id="why"></div>`
}
function layout() { A.innerHTML = `<div class="row"><h1 id="hd"></h1><span><button onclick="nasa()">🔬 NASA data</button> <button onclick="spd(0)" id="s0">Pause</button> <button onclick="spd(1)" id="s1" class="on">1×</button> <button onclick="spd(2)" id="s2">4×</button> <button onclick="spd(3)" id="s3">20×</button></span></div><div class="card"><b>Objective:</b> ${LV.obj}<br><small>💡 ${LV.hint}</small></div><div class="card" style="padding:0;overflow:hidden"><div id="v3d" style="height:300px;touch-action:none"></div></div><div class="grid" id="st"></div><div class="card"><canvas id="cv" width="900" height="150"></canvas><small>Drag the 3D view to look around. Green: power made (kW) · Orange: power used (kW) · Blue: battery % · Gray: dust opacity</small></div><div class="grid"><div class="card"><b>Controls</b><div class="row"><span>Heater set <b id="sv">20</b>°C</span><input type="range" min="10" max="24" value="20" oninput="S.set=+this.value;$('#sv').textContent=this.value"></div><div class="row"><button id="bg" onclick="S.gh=!S.gh;S.gh=+S.gh&&cfg.g" ${cfg.g ? '' : 'disabled'}>Greenhouse lights</button><button id="bx" onclick="S.ex=+!S.ex&&cfg.x" ${cfg.x ? '' : 'disabled'}>Ice miner</button></div><div class="row"><button onclick="cleanP()">Clean panels</button><button id="bs" onclick="S.sh=+!S.sh">Shelter crew</button><button onclick="repair()">Repair</button></div></div><div class="card"><b>Mission log</b><div id="log"></div></div></div><div id="why" style="margin-top:8px"></div><span id="ws">${['dust', 'power', 'air', 'rad', 'water'].map(why).join(' ')}</span>` }
function spd(i) { speed = i;[0, 1, 2, 3].forEach(j => $('#s' + j).className = j == i ? 'on' : '') }
const b = (l, v, m, u, bad) => `<div class="card ${bad ? 'alert' : ''}"><div class="row"><span>${l}</span><b>${v}</b></div><div class="bar"><i style="width:${Math.max(0, Math.min(100, v / m * 100))}%;background:${bad ? 'var(--wr)' : 'var(--ok)'}"></i></div><small>${u}</small></div>`;
function render() {
    const s = S, l = s.last || { gen: 0, used: 0, irr: 0, Ta: 0, ppm: 0, rate: 0 };
    $('#hd').textContent = `M${LV.id} · Sol ${Math.floor(s.t / 24) + 1}/${DAYS} · ${String(s.t % 24).padStart(2, '0')}:00`;
    $('#st').innerHTML = `<div class="card ${s.storm ? 'alert' : ''}"><b>Environment</b><br>Dust opacity ${s.tau.toFixed(1)}${s.storm ? ' (storm)' : ''}<br>Sunlight ${Math.round(l.irr * 100)}% · Outside ${l.Ta.toFixed(0)}°C<br>Radiation ${l.rate.toFixed(2)} mSv/h${s.spe ? ' <b class="A">SPIKE</b>' : ''}</div>` +
        b('Battery', Math.round(s.bat), cfg.b * 25 + 20, `Making ${l.gen.toFixed(1)} kW, using ${l.used.toFixed(1)} kW`, s.bat < cfg.b * 25 * .15) + b('Oxygen', Math.round(s.o2), 100, 'kg in tanks', s.o2 < 20) + b('CO2', Math.round(l.ppm), 15000, 'ppm in cabin', l.ppm > 5000) + b('Water', Math.round(s.h2o), 300, 'kg', s.h2o < 40) + b('Food', Math.round(s.food), 100, 'crew-days', s.food < 20) + b('Cabin temp', s.tin.toFixed(0), 35, '°C', s.tin < 8 || s.tin > 32) + b('Crew health', Math.round(s.hp), 100, 'average', s.hp < 60) + b('Radiation meter', Math.round(s.dose), 60, 'game limit 60 (abstraction)', s.dose > 40) + `<div class="card"><b>Systems</b><br>${['scr', 'oga', 'rec', 'heat'].map(k => `${k}: ${s.fail[k] ? '<b class="A">DOWN</b>' : 'ok'}`).join('<br>')}<br>Spare parts ${s.parts}${s.red ? ' · backup ready' : ''}</div>`;
    $('#log').innerHTML = s.log.slice(0, 12).join('<br>'); $('#bg').className = s.gh ? 'on' : ''; $('#bx').className = s.ex ? 'on' : ''; $('#bs').className = s.sh ? 'on' : ''; draw()
}
function draw() {
    const c = $('#cv'), x = c.getContext('2d'), H = S.hist, w = c.width, h = c.height; x.clearRect(0, 0, w, h); const css = getComputedStyle(document.documentElement); x.strokeStyle = css.getPropertyValue('--bd'); x.strokeRect(0, 0, w, h);
    const ln = (i, sc, col) => { x.strokeStyle = col; x.lineWidth = 2; x.beginPath(); H.forEach((p, k) => { const X = k / 95 * w, Y = h - 6 - Math.min(1, p[i] / sc) * (h - 12); k ? x.lineTo(X, Y) : x.moveTo(X, Y) }); x.stroke() };
    ln(0, Math.max(4, cfg.p * 4), '#8fd694'); ln(1, Math.max(4, cfg.p * 4), '#e8935f'); ln(2, 1, '#7fd0e8'); ln(3, 5, '#888')
}
function fin() {
    clearInterval(timer); if (V) { cancelAnimationFrame(V.raf); V = null } S.end = 1; const w = S.hp > 0 && (!LV.win || LV.win(S)), k = Object.entries(S.dmg).sort((a, b) => b[1] - a[1])[0], c = k ? k[0] : '',
        LS = { o2: ['Oxygen ran out.', 'The oxygen maker needs power and water. A blackout or failed unit becomes an air emergency within hours; backups and batteries buy time.'], co2: ['CO2 built up.', 'Scrubbers need power too. Air systems fail together when power fails.'], cold: ['The habitat froze.', 'Heating is a big power load at night and in storms. Insulation and shielding cut it.'], heat: ['The habitat overheated.', 'Thermal control works both ways.'], food: ['Food ran out.', 'Greenhouses need power, light, water and warmth. Stored food has to cover the gap.'], water: ['Water ran out.', 'Recycling, ice mining and smaller loads each stretch water at a cost in power or parts.'], rad: ['Radiation exposure got too high.', 'Shielding trades water, power or mass for safety. Shelter during spikes matters.'] },
        key = S.rec.filter(e => /Dust storm|BLACKOUT|failed|Battery|CO2|Oxygen|cold|Solar particle/i.test(e[1])).slice(0, 8).map(e => `<li>Sol ${Math.floor(e[0] / 24) + 1}, ${String(e[0] % 24).padStart(2, '0')}:00 — ${e[1]}</li>`).join('');
    A.innerHTML = `<h1>${w ? 'Mission complete' : 'Mission failed'}</h1><div class="card">${w ? `<p>Your crew survived ${DAYS} sols. Final health ${Math.round(S.hp)}, radiation meter ${Math.round(S.dose)}/60, lowest-risk path found. Compare a different design on the same seed (${seed}).</p>` : `<p><b>${S.hp > 0 ? 'Objective not met: ' + LV.winMsg : (LS[c] || ['The crew did not survive.'])[0]}</b></p><p>What led to it:</p><ul>${key}</ul><p><b>Engineering lesson:</b> ${S.hp > 0 ? LV.lesson : (LS[c] || ['', ''])[1]}</p>`}${lvEnd(w)}<small>Numbers are modeled; see the data labels on the start screen. Real inputs: Curiosity RAD radiation and SWIM ice maps.</small></div><p>${endBtns(w)}</p>`
}